# CS405 Data Mining
## Mélanie Moal, Bastien Fournier, Vincent Turel, Julien Whitfield
### 25 november 2021

## KNN

In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.datasets import mnist
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_auc_score
import random
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

In [58]:
# preprocessing of the data

(train_images, train_labels),(test_images,test_labels)=mnist.load_data()
#print(data.shape)

print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

# reshaping : training set contains 60000 and the validation set contains 10000 images
train_images=train_images.reshape((60000,28*28))
test_images=test_images.reshape((10000,28*28))

x = random.randrange(55000)
y = random.randrange(8000)
train_images_k = train_images[x:x+5000]
train_labels_k = train_labels[x:x+5000]
test_images_k = test_images[y:y+2000]
test_labels_k = test_labels[y:y+2000]

print(train_images_k.shape)
print(test_images_k.shape)
print(train_images.shape)
print(test_images.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
(5000, 784)
(2000, 784)
(60000, 784)
(10000, 784)


In [60]:
# we try different values for k on the sample (train_images_k, test_images_k)
score = []
k_max = 0
score_max = 0
matrix_max = []
for k in range(1, 15):
  print('Begin KNN with k=',k)
  classifier = KNeighborsClassifier(n_neighbors=k)
  classifier = classifier.fit(train_images_k, train_labels_k)
  pred = classifier.predict(test_images_k)
  accuracy = accuracy_score(test_labels_k, pred)
  score.append(accuracy)
  if (accuracy > score_max):
    score_max = accuracy
    k_max = k
    matrix_max = confusion_matrix(test_labels_k, pred)

print("\n---------------\n")
print("Best k : ", k_max)
print("Confusion Matrix:\n", matrix_max)
print("Accuracy: ",score_max)
print("\n---------------\n")

# By running this cell we get the optimal k 

Begin KNN with k= 1
Begin KNN with k= 2
Begin KNN with k= 3
Begin KNN with k= 4
Begin KNN with k= 5
Begin KNN with k= 6
Begin KNN with k= 7
Begin KNN with k= 8
Begin KNN with k= 9
Begin KNN with k= 10
Begin KNN with k= 11
Begin KNN with k= 12
Begin KNN with k= 13
Begin KNN with k= 14
Accuracy:  0.8985
Confusion Matrix:
 [[180   0   0   0   0   0   1   0   2   0]
 [  0 213   0   1   0   0   1   0   0   0]
 [  9  11 176   3   1   0   2   6   2   0]
 [  0   3   2 192   0   4   0   3   2   0]
 [  0   3   0   0 174   0   4   1   0  23]
 [  4   1   0  15   0 162   3   2   0   3]
 [  4   4   0   0   0   3 179   0   0   0]
 [  0  15   0   0   2   0   0 188   0   5]
 [  3   4   3   9   5  14   2   2 154   2]
 [  3   4   0   2   1   1   0   3   0 179]]
Best k :  5

---------------



In [46]:
# So now we can do the KNN method with the optimal k on the whole data (train_images, test_images)
clf=KNeighborsClassifier(n_neighbors=k_max)
clf.fit(train_images,train_labels)

# predictions
pred_val=clf.predict(test_images)

# confusion matrix :
print("---------------------------")
print(confusion_matrix(test_labels,pred_val))

# accuracy
exactitude_val=np.sum(test_labels==pred_val)/test_images.shape[0]
print('accuracy : ',exactitude_val)

# classification report
print(classification_report(test_labels,pred_val))


[[5893    4    2    0    1    4   14    2    1    2]
 [   1 6721    7    0    0    0    1    9    1    2]
 [  24   36 5821   10    7    4    6   41    6    3]
 [   2   12   26 6001    0   34    2   21   17   16]
 [   3   39    1    1 5724    0    6    5    2   61]
 [  13    5    3   35    5 5302   38    3    3   14]
 [  11    9    0    0    4   12 5882    0    0    0]
 [   1   46   10    2    7    0    0 6165    0   34]
 [  15   59   10   40   20   51   14   11 5591   40]
 [  10    6    5   22   34    9    2   39    7 5815]]
[[ 974    1    1    0    0    1    2    1    0    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [  11    8  991    2    1    0    1   15    3    0]
 [   0    3    3  976    1   13    1    6    3    4]
 [   3    7    0    0  944    0    4    2    1   21]
 [   5    0    0   12    2  862    4    1    2    4]
 [   5    3    0    0    3    2  945    0    0    0]
 [   0   22    4    0    3    0    0  988    0   11]
 [   8    3    5   13    6   12    5    5  91

ValueError: multi_class must be in ('ovo', 'ovr')